micronaut:
  application:
    name: productsService

grpc:
  server:
    for-port: 50052
  channels:
    productService:
      target: localhost:50052
      plaintext: true
#  channels:
#    productservice:
#      target: "https://localhost:5001"
#      plaintext: true
#    keyManager:
#      address: '${KEY_MANAGER_HOST:localhost}:${KEY_MANAGER_PORT:50052}'


datasources:
  default:
    url: jdbc:h2:mem:devTest;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ''
    driver-class-name: org.h2.Driver
    dialect: H2
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
